### PR TITLE
COLLEGE NAME UPDATE

### PR DESCRIPTION
**Pull request by ujjwalsittu**
CAN VERIFY BY VISITNG OFFICIAL WEBSITE gita.edu.in

AND ADDITION OF COLLEGE GANDHI ENGINEERING COLLEG - gec.edu.in

### CODE REVIEW

**Comment by jonmarkgo** [comment]
It is unclear from the official website which name should be used: 
Screenshot 2023-01-30 at 3 53 36 PM

**Comment by Anup-Gautam** [comment]
An Addition of University, Fisk University, Nashville, Tennesse, USA

**Comment by ujjwalsittu** [comment]
> It is unclear from the official website which name should be used:
> Screenshot 2023-01-30 at 3 53 36 PM

The official Name of College is 

GITA Autonomous College,

it is also in our student ID Card

**Comment by erinosher** [comment]
Hey there 👋 

Thanks for contributing!

We've changed how the `schools.csv` file is maintained and generated, and are no longer accepting pull requests. 

Please check the updated version of the file for your school. If it is still not there, you'll be able to add new schools from within [my.mlh.io](https://my.mlh.io) next week.

Cheers,
Erin and the MLH Team

**Pull request closed without merging**
