### PR TITLE
Add University of Zagreb to schools list.

### PR DESCRIPTION
**Pull request by austinhartzheim**
MadHacks has received an application from the University of Zagreb in Croatia. This PR adds that university to the list of schools.

### CODE REVIEW

**Comment by mparker97** [comment]
MadHacks has also received multiple applications from Marquette University.

**Comment by austinhartzheim** [comment]
@mparker97 Thanks. I've added Marquette University to this PR as well.

**Comment by mparker97** [comment]
Add Colgate University (Hamilton, NY)

**Comment by austinhartzheim** [comment]
@mparker97 Done. I also added Adlai E. Stevenson High School based on your mention from Slack.
@Shy It looks like you are managing this repo. Is there anything we need to do to get this merged? Or would you prefer batching the edits?

**Pull request merged**
