### PR TITLE
Update U of Cincinnati in schools.csv

### PR DESCRIPTION
**Pull request by noahbass**
'The University of Cincinnati' -> 'University of Cincinnati'

👍

### CODE REVIEW

**Comment by theycallmeswift** [comment]
Hey @noahbass.  Thanks for sending in this PR.  Looking at the school's about page, it says "The University of Cincinnati".  Do you have some information that indicates we should drop the "the"? http://www.uc.edu/about.html

**Comment by noahbass** [comment]
This is a fair question!

We typically don't capitalize the 'the' when using UC in a sentence. Ex: "Computer science is the coolest major at the University of Cincinnati!"

An example from the https://uc.edu/about.html page:

untitled


And from the footer of https://uc.edu: "© 2017 University of Cincinnati"

A school that keeps the 'the', such as The University of Texas at Austin, capitalizes in all references: "Like the state it calls home, The University of Texas at Austin is a bold, ambitious leader."

Including the footer https://www.utexas.edu: "© The University of Texas at Austin 2018"

**Comment by jonmarkgo** [comment]
This is good to merge from my end

**Comment by chibnguyen** [comment]
That’s fine with me so long as @jonmarkgo you are able to change any scoring related to the schools name previously.

**Comment by theycallmeswift** [comment]
@chibnguyen that's a fair point.  @jonmarkgo does anything need to change on internal systems or can I go ahead and merge this?

**Pull request merged**
