### PR TITLE
Translate membership guidelines to Spanish

### PR DESCRIPTION
**Pull request by tfogo**

### CODE REVIEW

**Comment by bih** [comment]
Does it not make sense to have a multi-language folder structure as follows:

- `en/code-of-conduct.md`
- `en/community-values.md`
- `en/data-sharing.md`
- `en/disciplinary-policy.md`
- `en/incident-response.md`
- `en/privacy-policy.md`

and then just create a new folder (i.e. `es` in this case) for other languages? It'll be way more structured for when we add other languages down the line.

And for the sake of avoiding complexity - is it worth renaming the file names? It'll be easier for the people who manage this over the coming months and years if we use the same filenames, but the content is in the language that it is said out to be in.

**Comment by tfogo** [comment]
Yep, that's a good suggestion for the folders. I'll use the `español` branch as a working branch for the time being and I'll switch it over to folders. Then we can merge it into master.

Good point about the file names. The one thing is when people create pdfs of the files to put on the website, I think the pdfs should be called the title in the language of the document. Maybe we should add the steps of creating and uploading the static documents to the readme. I know Shy has been frustrated that he couldn't do it himself in the past. If we did that we could document what the titles should be for each document in each language and keep all the filenames on GitHub in English.

**Comment by tfogo** [comment]
(should have tagged issue #1)

**Comment by bih** [comment]
@tfogo Well, the plan I had in mind was eventually to have making updates to `master` automatically generate the appropriate PDF documents and upload them to Amazon S3.

There isn't a timeline for that as of yet. It will be something that'll be a part of MLH Engineering's automation project over the coming months though.

In terms of having the filenames localised on the website, one way we can do that is to incorporate [YAML Front Matter](https://jekyllrb.com/docs/frontmatter/) to define the localised name for the document. That'll make manually uploading them easier and for the future, any software we write will be able to read the YAML Front Matter and do that automatically.

An example of what I mean for the Membership Guidelines in Spanish:

```
---
name: Lineamientos Para Los Miembros
---

# Lineamientos para los miembros

Este documento detalla los lineamientos generales para los miembros participantes en la Major League Hacking (MLH). A efectos de facilitar las tareas de los organizadores y mejorar la experiencia de los hackers, MLH Proporciona los siguientes recursos y beneficios a todos los eventos miembros de MLH.

## Paquete básico

Todos los hackathons reciben los siguientes beneficios durante los eventos MLH:

...
```

**Comment by tfogo** [comment]
That sounds good @bih

**Comment by theycallmeswift** [comment]
We need to translate this to Spanish, but this is now outdated.  Closing

**Pull request closed without merging**
