### PR TITLE
Add University - University of Wisconsin Eau Claire

### PR DESCRIPTION
**Pull request by WilliamTomOBrien**

### CODE REVIEW

**Comment by theycallmeswift** [comment]
Looks like this pull request got messed up @WilliamTomOBrien.  Were you trying to add "University of Wisconsin Eau Claire" to the list of schools?

**Comment by WilliamTomOBrien** [comment]
Yeah, I apologize.

**Comment by austinhartzheim** [comment]
#31 Adds University of Wisconsin - Eau Claire, along with other schools from the UW system. I didn't realize this PR was already open, but it doesn't seem to change the schools list like the title suggests.

**Comment by jonmarkgo** [comment]
Rejected. Merged #31 instead

**Comment by WilliamTomOBrien** [comment]
Yeah, I apologize, I was fairly confused as to what to do!

**Pull request closed without merging**
